IllegalValueException: add `cause` constructor
Sometimes, IllegalValueExceptions are caused by other exceptions. This
new `cause` constructor allows us to tell the caller which exception
that is.